services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d  # Voor init scripts
    networks:
      - app-network
 
  # Node.js Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nodejs_api
    restart: always
    ports:
      - "3000:3000"  # Of welke poort je API gebruikt
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    volumes:
      - ./backend:/index
      - /index/node_modules  # Prevent overwriting node_modules
    networks:
      - app-network
 
  # Svelte Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: svelte_frontend
    restart: always
    ports:
      - "5173:5173"  # Vite default port, of 3001 voor production
    environment:
      - VITE_API_URL=http://backend:3000  # URL naar je backend
    depends_on:
      - backend
    volumes:
      - ./frontend:/index
      - /index/node_modules
    networks:
      - app-network
 
volumes:
  postgres_data:
 
networks:
  app-network:
    driver: bridge