version: '3.8'
 
services:
  db:
    image: postgres:latest
    container_name: bankserver_db
    restart: always
    environment:
      POSTGRES_PASSWORD: chickenjockey
    ports:
      - "5432:5432"         
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
 